[[customizations.user]]
name = "cthtrifork"
password = ""
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB0hdmkkeD2IWZfMYQt/JSNE9QV7ky9QSb9yqpfPHEKE cthtrifork@github/110127566 # ssh-import-id gh:cthtrifork"
groups = ["wheel"]

[[customizations.user]]
name = "cthtrifork-home"
password = ""
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIO6lC/ygAhNiAQ2LGQa9EsOPSEVao2Yb26ZdFrAoldH3lqlV8eo1HYGbVcupBL42IcB6JgVTzd+3zbDs6/bMLPzXdp1MFnKm6zAT4WslibN8JSrsEh++8CA5nuqEtup3QB/GuLMRRZab7cparrAXLEWNG/fRkydTxiEtWM7ZbRANm3jb2rEmpRyxFq8+3hqtqJbSks43nZ9w/2Ej/Zwd65M3NmQE/zl4nkdw/hBqHUgdVZh+7SVgXn+HNtp52XeRG092PcSfMUQtgvjRLXymY4uvkR0SgtFG2k5IddWnckE/Q6X02H7AHnIGPXGiI/v1R4pb+OupPMBQrUp8aXfIhMU3YKSL6jsb5xBOgXxyCfz2Kl2EzMf1o/a1Q5Yzc4bl/fDvKOmlF+kxnsojsR2ZNANu/FLm2xGuGcDWLLAkABqIi0Df5UymmLLgQaPtcUMAVhAtN6UyjgSCVuVnY9N6RJ7+YgsKqXoeDca5jz8+2StjDu0n+SDYlIkMvprdEYjcI3YNe/mBRkAVjjAxOzhJxQj/bZ6/R0kBNxp46yokDcZkWIscUwSFDN+kck3CjTxkjD71yPLzZLXGUMphnUCOF8i6H0a+qi3ZhIJeBAX8OkPByhW+qZsJXhlGzygiq/HktlHcdk+5LaqH0VjnL37cuLaTBET7VLrARdOgaFrYHhw== cthtrifork@github/109003985 # ssh-import-id gh:cthtrifork"
groups = ["wheel"]

[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"