name: Create vmdk
on:
  workflow_dispatch:

jobs:
  create-vmdk:
    name: Build vmdk
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: true
      matrix:
        image:
          - IMAGE_NAME: homeserver-centos-bootc-vmdk
            CONTEXT: .
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create VMDK image
        id: create-vmdk
        uses: ublue-os/bootc-image-builder-action@main
        with:
          config-file: ${{ matrix.image.CONTEXT }}/config.toml
          type: iso
          rootfs: xfs
          image: ghcr.io/${{ github.repository }}/${{ matrix.image.IMAGE_NAME }}:latest

      - name: Upload VMDK artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ matrix.image.IMAGE_NAME }}

          path: ${{ steps.create-vmdk.outputs.output-path }}

