name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *" # workflows runs every 2 hours
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.9
        env:
          RENOVATE_PAT_TOKEN: '${{ secrets.PAT_RENOVATEBOT }}'
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_X_GITHUB_HOST_RULES: 'true'
